name: Cypress Tests
defaults:
  run:
    working-directory: ./playground
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          install-command: yarn install --frozen-lockfile
          working-directory: ./playground
